/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_AccelOrDecel_H_
#define	_AccelOrDecel_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AccelOrDecel {
	AccelOrDecel_accelerate	= 0,
	AccelOrDecel_decelerate	= 1
} e_AccelOrDecel;

/* AccelOrDecel */
typedef long	 AccelOrDecel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AccelOrDecel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AccelOrDecel;
extern const asn_INTEGER_specifics_t asn_SPC_AccelOrDecel_specs_1;
asn_struct_free_f AccelOrDecel_free;
asn_struct_print_f AccelOrDecel_print;
asn_constr_check_f AccelOrDecel_constraint;
ber_type_decoder_f AccelOrDecel_decode_ber;
der_type_encoder_f AccelOrDecel_encode_der;
xer_type_decoder_f AccelOrDecel_decode_xer;
xer_type_encoder_f AccelOrDecel_encode_xer;
oer_type_decoder_f AccelOrDecel_decode_oer;
oer_type_encoder_f AccelOrDecel_encode_oer;
per_type_decoder_f AccelOrDecel_decode_uper;
per_type_encoder_f AccelOrDecel_encode_uper;
per_type_decoder_f AccelOrDecel_decode_aper;
per_type_encoder_f AccelOrDecel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _AccelOrDecel_H_ */
#include "asn_internal.h"
