/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ClusterProfiles_H_
#define	_ClusterProfiles_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ClusterProfiles {
	ClusterProfiles_pedestrian	= 0,
	ClusterProfiles_bicyclist	= 1,
	ClusterProfiles_motorcyclist	= 2,
	ClusterProfiles_animal	= 3
} e_ClusterProfiles;

/* ClusterProfiles */
typedef BIT_STRING_t	 ClusterProfiles_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ClusterProfiles_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ClusterProfiles;
asn_struct_free_f ClusterProfiles_free;
asn_struct_print_f ClusterProfiles_print;
asn_constr_check_f ClusterProfiles_constraint;
ber_type_decoder_f ClusterProfiles_decode_ber;
der_type_encoder_f ClusterProfiles_encode_der;
xer_type_decoder_f ClusterProfiles_decode_xer;
xer_type_encoder_f ClusterProfiles_encode_xer;
oer_type_decoder_f ClusterProfiles_decode_oer;
oer_type_encoder_f ClusterProfiles_encode_oer;
per_type_decoder_f ClusterProfiles_decode_uper;
per_type_encoder_f ClusterProfiles_encode_uper;
per_type_decoder_f ClusterProfiles_decode_aper;
per_type_encoder_f ClusterProfiles_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ClusterProfiles_H_ */
#include "asn_internal.h"
