/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ClusterBoundingBoxShape_H_
#define	_ClusterBoundingBoxShape_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AreaRectangle.h"
#include "AreaCircular.h"
#include "AreaPolygon.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ClusterBoundingBoxShape_PR {
	ClusterBoundingBoxShape_PR_NOTHING,	/* No components present */
	ClusterBoundingBoxShape_PR_clusterRectangle,
	ClusterBoundingBoxShape_PR_clusterCircle,
	ClusterBoundingBoxShape_PR_clusterPolygon
	/* Extensions may appear below */
	
} ClusterBoundingBoxShape_PR;

/* ClusterBoundingBoxShape */
typedef struct ClusterBoundingBoxShape {
	ClusterBoundingBoxShape_PR present;
	union ClusterBoundingBoxShape_u {
		AreaRectangle_t	 clusterRectangle;
		AreaCircular_t	 clusterCircle;
		AreaPolygon_t	 clusterPolygon;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ClusterBoundingBoxShape_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ClusterBoundingBoxShape;
extern asn_CHOICE_specifics_t asn_SPC_ClusterBoundingBoxShape_specs_1;
extern asn_TYPE_member_t asn_MBR_ClusterBoundingBoxShape_1[3];
extern asn_per_constraints_t asn_PER_type_ClusterBoundingBoxShape_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ClusterBoundingBoxShape_H_ */
#include "asn_internal.h"
