/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ClusterId_H_
#define	_ClusterId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ClusterId */
typedef long	 ClusterId_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ClusterId_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ClusterId;
asn_struct_free_f ClusterId_free;
asn_struct_print_f ClusterId_print;
asn_constr_check_f ClusterId_constraint;
ber_type_decoder_f ClusterId_decode_ber;
der_type_encoder_f ClusterId_encode_der;
xer_type_decoder_f ClusterId_decode_xer;
xer_type_encoder_f ClusterId_encode_xer;
oer_type_decoder_f ClusterId_decode_oer;
oer_type_encoder_f ClusterId_encode_oer;
per_type_decoder_f ClusterId_decode_uper;
per_type_encoder_f ClusterId_encode_uper;
per_type_decoder_f ClusterId_decode_aper;
per_type_encoder_f ClusterId_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ClusterId_H_ */
#include "asn_internal.h"
