/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_PosConfidenceEllipse_H_
#define	_ETSI_ITS_CDD_PosConfidenceEllipse_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_SemiAxisLength.h"
#include "ETSI-ITS-CDD_HeadingValue.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ETSI-ITS-CDD_PosConfidenceEllipse */
typedef struct ETSI_ITS_CDD_PosConfidenceEllipse {
	ETSI_ITS_CDD_SemiAxisLength_t	 semiMajorConfidence;
	ETSI_ITS_CDD_SemiAxisLength_t	 semiMinorConfidence;
	ETSI_ITS_CDD_HeadingValue_t	 semiMajorOrientation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETSI_ITS_CDD_PosConfidenceEllipse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_PosConfidenceEllipse;
extern asn_SEQUENCE_specifics_t asn_SPC_ETSI_ITS_CDD_PosConfidenceEllipse_specs_1;
extern asn_TYPE_member_t asn_MBR_ETSI_ITS_CDD_PosConfidenceEllipse_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_PosConfidenceEllipse_H_ */
#include "asn_internal.h"
