/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_DeltaReferencePosition_H_
#define	_ETSI_ITS_CDD_DeltaReferencePosition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_DeltaLatitude.h"
#include "ETSI-ITS-CDD_DeltaLongitude.h"
#include "ETSI-ITS-CDD_DeltaAltitude.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ETSI-ITS-CDD_DeltaReferencePosition */
typedef struct ETSI_ITS_CDD_DeltaReferencePosition {
	ETSI_ITS_CDD_DeltaLatitude_t	 deltaLatitude;
	ETSI_ITS_CDD_DeltaLongitude_t	 deltaLongitude;
	ETSI_ITS_CDD_DeltaAltitude_t	 deltaAltitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETSI_ITS_CDD_DeltaReferencePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_DeltaReferencePosition;
extern asn_SEQUENCE_specifics_t asn_SPC_ETSI_ITS_CDD_DeltaReferencePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_ETSI_ITS_CDD_DeltaReferencePosition_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_DeltaReferencePosition_H_ */
#include "asn_internal.h"
