/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_RoadworksSubCauseCode_H_
#define	_ETSI_ITS_CDD_RoadworksSubCauseCode_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_RoadworksSubCauseCode {
	ETSI_ITS_CDD_RoadworksSubCauseCode_unavailable	= 0,
	ETSI_ITS_CDD_RoadworksSubCauseCode_majorRoadworks	= 1,
	ETSI_ITS_CDD_RoadworksSubCauseCode_roadMarkingWork	= 2,
	ETSI_ITS_CDD_RoadworksSubCauseCode_slowMovingRoadMaintenance	= 3,
	ETSI_ITS_CDD_RoadworksSubCauseCode_shortTermStationaryRoadworks	= 4,
	ETSI_ITS_CDD_RoadworksSubCauseCode_streetCleaning	= 5,
	ETSI_ITS_CDD_RoadworksSubCauseCode_winterService	= 6
} e_ETSI_ITS_CDD_RoadworksSubCauseCode;

/* ETSI-ITS-CDD_RoadworksSubCauseCode */
typedef long	 ETSI_ITS_CDD_RoadworksSubCauseCode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ETSI_ITS_CDD_RoadworksSubCauseCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_RoadworksSubCauseCode;
asn_struct_free_f ETSI_ITS_CDD_RoadworksSubCauseCode_free;
asn_struct_print_f ETSI_ITS_CDD_RoadworksSubCauseCode_print;
asn_constr_check_f ETSI_ITS_CDD_RoadworksSubCauseCode_constraint;
ber_type_decoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_RoadworksSubCauseCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_RoadworksSubCauseCode_H_ */
#include "asn_internal.h"
