/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_SteeringWheelAngleValue_H_
#define	_ETSI_ITS_CDD_SteeringWheelAngleValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_SteeringWheelAngleValue {
	ETSI_ITS_CDD_SteeringWheelAngleValue_negativeOutOfRange	= -511,
	ETSI_ITS_CDD_SteeringWheelAngleValue_positiveOutOfRange	= 511,
	ETSI_ITS_CDD_SteeringWheelAngleValue_unavailable	= 512
} e_ETSI_ITS_CDD_SteeringWheelAngleValue;

/* ETSI-ITS-CDD_SteeringWheelAngleValue */
typedef long	 ETSI_ITS_CDD_SteeringWheelAngleValue_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ETSI_ITS_CDD_SteeringWheelAngleValue_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_SteeringWheelAngleValue;
asn_struct_free_f ETSI_ITS_CDD_SteeringWheelAngleValue_free;
asn_struct_print_f ETSI_ITS_CDD_SteeringWheelAngleValue_print;
asn_constr_check_f ETSI_ITS_CDD_SteeringWheelAngleValue_constraint;
ber_type_decoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_SteeringWheelAngleValue_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_SteeringWheelAngleValue_H_ */
#include "asn_internal.h"
