/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_Speed_H_
#define	_ETSI_ITS_CDD_Speed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_SpeedValue.h"
#include "ETSI-ITS-CDD_SpeedConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ETSI-ITS-CDD_Speed */
typedef struct ETSI_ITS_CDD_Speed {
	ETSI_ITS_CDD_SpeedValue_t	 speedValue;
	ETSI_ITS_CDD_SpeedConfidence_t	 speedConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETSI_ITS_CDD_Speed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_Speed;
extern asn_SEQUENCE_specifics_t asn_SPC_ETSI_ITS_CDD_Speed_specs_1;
extern asn_TYPE_member_t asn_MBR_ETSI_ITS_CDD_Speed_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_Speed_H_ */
#include "asn_internal.h"
