/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_YawRate_H_
#define	_ETSI_ITS_CDD_YawRate_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_YawRateValue.h"
#include "ETSI-ITS-CDD_YawRateConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ETSI-ITS-CDD_YawRate */
typedef struct ETSI_ITS_CDD_YawRate {
	ETSI_ITS_CDD_YawRateValue_t	 yawRateValue;
	ETSI_ITS_CDD_YawRateConfidence_t	 yawRateConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETSI_ITS_CDD_YawRate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_YawRate;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_YawRate_H_ */
#include "asn_internal.h"
