/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_PositionOfOccupants_H_
#define	_ETSI_ITS_CDD_PositionOfOccupants_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_PositionOfOccupants {
	ETSI_ITS_CDD_PositionOfOccupants_row1LeftOccupied	= 0,
	ETSI_ITS_CDD_PositionOfOccupants_row1RightOccupied	= 1,
	ETSI_ITS_CDD_PositionOfOccupants_row1MidOccupied	= 2,
	ETSI_ITS_CDD_PositionOfOccupants_row1NotDetectable	= 3,
	ETSI_ITS_CDD_PositionOfOccupants_row1NotPresent	= 4,
	ETSI_ITS_CDD_PositionOfOccupants_row2LeftOccupied	= 5,
	ETSI_ITS_CDD_PositionOfOccupants_row2RightOccupied	= 6,
	ETSI_ITS_CDD_PositionOfOccupants_row2MidOccupied	= 7,
	ETSI_ITS_CDD_PositionOfOccupants_row2NotDetectable	= 8,
	ETSI_ITS_CDD_PositionOfOccupants_row2NotPresent	= 9,
	ETSI_ITS_CDD_PositionOfOccupants_row3LeftOccupied	= 10,
	ETSI_ITS_CDD_PositionOfOccupants_row3RightOccupied	= 11,
	ETSI_ITS_CDD_PositionOfOccupants_row3MidOccupied	= 12,
	ETSI_ITS_CDD_PositionOfOccupants_row3NotDetectable	= 13,
	ETSI_ITS_CDD_PositionOfOccupants_row3NotPresent	= 14,
	ETSI_ITS_CDD_PositionOfOccupants_row4LeftOccupied	= 15,
	ETSI_ITS_CDD_PositionOfOccupants_row4RightOccupied	= 16,
	ETSI_ITS_CDD_PositionOfOccupants_row4MidOccupied	= 17,
	ETSI_ITS_CDD_PositionOfOccupants_row4NotDetectable	= 18,
	ETSI_ITS_CDD_PositionOfOccupants_row4NotPresent	= 19
} e_ETSI_ITS_CDD_PositionOfOccupants;

/* ETSI-ITS-CDD_PositionOfOccupants */
typedef BIT_STRING_t	 ETSI_ITS_CDD_PositionOfOccupants_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_PositionOfOccupants;
asn_struct_free_f ETSI_ITS_CDD_PositionOfOccupants_free;
asn_struct_print_f ETSI_ITS_CDD_PositionOfOccupants_print;
asn_constr_check_f ETSI_ITS_CDD_PositionOfOccupants_constraint;
ber_type_decoder_f ETSI_ITS_CDD_PositionOfOccupants_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_PositionOfOccupants_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_PositionOfOccupants_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_PositionOfOccupants_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_PositionOfOccupants_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_PositionOfOccupants_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_PositionOfOccupants_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_PositionOfOccupants_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_PositionOfOccupants_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_PositionOfOccupants_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_PositionOfOccupants_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_PositionOfOccupants_H_ */
#include "asn_internal.h"
