/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_EventPoint_H_
#define	_ETSI_ITS_CDD_EventPoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_DeltaReferencePosition.h"
#include "ETSI-ITS-CDD_PathDeltaTime.h"
#include "ETSI-ITS-CDD_InformationQuality.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ETSI-ITS-CDD_EventPoint */
typedef struct ETSI_ITS_CDD_EventPoint {
	ETSI_ITS_CDD_DeltaReferencePosition_t	 eventPosition;
	ETSI_ITS_CDD_PathDeltaTime_t	*eventDeltaTime;	/* OPTIONAL */
	ETSI_ITS_CDD_InformationQuality_t	 informationQuality;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETSI_ITS_CDD_EventPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_EventPoint;
extern asn_SEQUENCE_specifics_t asn_SPC_ETSI_ITS_CDD_EventPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_ETSI_ITS_CDD_EventPoint_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_EventPoint_H_ */
#include "asn_internal.h"
