/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_ProtectedCommunicationZone_H_
#define	_ETSI_ITS_CDD_ProtectedCommunicationZone_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ETSI-ITS-CDD_ProtectedZoneType.h"
#include "ETSI-ITS-CDD_TimestampIts.h"
#include "ETSI-ITS-CDD_Latitude.h"
#include "ETSI-ITS-CDD_Longitude.h"
#include "ETSI-ITS-CDD_ProtectedZoneRadius.h"
#include "ProtectedZoneId.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ETSI-ITS-CDD_ProtectedCommunicationZone */
typedef struct ETSI_ITS_CDD_ProtectedCommunicationZone {
	ETSI_ITS_CDD_ProtectedZoneType_t	 protectedZoneType;
	ETSI_ITS_CDD_TimestampIts_t	*expiryTime;	/* OPTIONAL */
	ETSI_ITS_CDD_Latitude_t	 protectedZoneLatitude;
	ETSI_ITS_CDD_Longitude_t	 protectedZoneLongitude;
	ETSI_ITS_CDD_ProtectedZoneRadius_t	*protectedZoneRadius;	/* OPTIONAL */
	ProtectedZoneId_t	*protectedZoneId;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETSI_ITS_CDD_ProtectedCommunicationZone_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_ProtectedCommunicationZone;
extern asn_SEQUENCE_specifics_t asn_SPC_ETSI_ITS_CDD_ProtectedCommunicationZone_specs_1;
extern asn_TYPE_member_t asn_MBR_ETSI_ITS_CDD_ProtectedCommunicationZone_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_ProtectedCommunicationZone_H_ */
#include "asn_internal.h"
