/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_Traces_H_
#define	_ETSI_ITS_CDD_Traces_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Path;

/* ETSI-ITS-CDD_Traces */
typedef struct ETSI_ITS_CDD_Traces {
	A_SEQUENCE_OF(struct Path) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ETSI_ITS_CDD_Traces_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_Traces;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Path.h"

#endif	/* _ETSI_ITS_CDD_Traces_H_ */
#include "asn_internal.h"
