/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_RelevanceDistance_H_
#define	_ETSI_ITS_CDD_RelevanceDistance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_RelevanceDistance {
	ETSI_ITS_CDD_RelevanceDistance_lessThan50m	= 0,
	ETSI_ITS_CDD_RelevanceDistance_lessThan100m	= 1,
	ETSI_ITS_CDD_RelevanceDistance_lessThan200m	= 2,
	ETSI_ITS_CDD_RelevanceDistance_lessThan500m	= 3,
	ETSI_ITS_CDD_RelevanceDistance_lessThan1000m	= 4,
	ETSI_ITS_CDD_RelevanceDistance_lessThan5km	= 5,
	ETSI_ITS_CDD_RelevanceDistance_lessThan10km	= 6,
	ETSI_ITS_CDD_RelevanceDistance_over10km	= 7
} e_ETSI_ITS_CDD_RelevanceDistance;

/* ETSI-ITS-CDD_RelevanceDistance */
typedef long	 ETSI_ITS_CDD_RelevanceDistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_RelevanceDistance;
asn_struct_free_f ETSI_ITS_CDD_RelevanceDistance_free;
asn_struct_print_f ETSI_ITS_CDD_RelevanceDistance_print;
asn_constr_check_f ETSI_ITS_CDD_RelevanceDistance_constraint;
ber_type_decoder_f ETSI_ITS_CDD_RelevanceDistance_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_RelevanceDistance_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_RelevanceDistance_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_RelevanceDistance_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_RelevanceDistance_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_RelevanceDistance_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_RelevanceDistance_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_RelevanceDistance_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_RelevanceDistance_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_RelevanceDistance_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_RelevanceDistance_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_RelevanceDistance_H_ */
#include "asn_internal.h"
