/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_CauseCodeType_H_
#define	_ETSI_ITS_CDD_CauseCodeType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_CauseCodeType {
	ETSI_ITS_CDD_CauseCodeType_trafficCondition	= 1,
	ETSI_ITS_CDD_CauseCodeType_accident	= 2,
	ETSI_ITS_CDD_CauseCodeType_roadworks	= 3,
	ETSI_ITS_CDD_CauseCodeType_impassability	= 5,
	ETSI_ITS_CDD_CauseCodeType_adverseWeatherCondition_Adhesion	= 6,
	ETSI_ITS_CDD_CauseCodeType_aquaplaning	= 7,
	ETSI_ITS_CDD_CauseCodeType_hazardousLocation_SurfaceCondition	= 9,
	ETSI_ITS_CDD_CauseCodeType_hazardousLocation_ObstacleOnTheRoad	= 10,
	ETSI_ITS_CDD_CauseCodeType_hazardousLocation_AnimalOnTheRoad	= 11,
	ETSI_ITS_CDD_CauseCodeType_humanPresenceOnTheRoad	= 12,
	ETSI_ITS_CDD_CauseCodeType_wrongWayDriving	= 14,
	ETSI_ITS_CDD_CauseCodeType_rescueAndRecoveryWorkInProgress	= 15,
	ETSI_ITS_CDD_CauseCodeType_adverseWeatherCondition_ExtremeWeatherCondition	= 17,
	ETSI_ITS_CDD_CauseCodeType_adverseWeatherCondition_Visibility	= 18,
	ETSI_ITS_CDD_CauseCodeType_adverseWeatherCondition_Precipitation	= 19,
	ETSI_ITS_CDD_CauseCodeType_violence	= 20,
	ETSI_ITS_CDD_CauseCodeType_slowVehicle	= 26,
	ETSI_ITS_CDD_CauseCodeType_dangerousEndOfQueue	= 27,
	ETSI_ITS_CDD_CauseCodeType_vehicleBreakdown	= 91,
	ETSI_ITS_CDD_CauseCodeType_postCrash	= 92,
	ETSI_ITS_CDD_CauseCodeType_humanProblem	= 93,
	ETSI_ITS_CDD_CauseCodeType_stationaryVehicle	= 94,
	ETSI_ITS_CDD_CauseCodeType_emergencyVehicleApproaching	= 95,
	ETSI_ITS_CDD_CauseCodeType_hazardousLocation_DangerousCurve	= 96,
	ETSI_ITS_CDD_CauseCodeType_collisionRisk	= 97,
	ETSI_ITS_CDD_CauseCodeType_signalViolation	= 98,
	ETSI_ITS_CDD_CauseCodeType_dangerousSituation	= 99,
	ETSI_ITS_CDD_CauseCodeType_railwayLevelCrossing	= 100
} e_ETSI_ITS_CDD_CauseCodeType;

/* ETSI-ITS-CDD_CauseCodeType */
typedef long	 ETSI_ITS_CDD_CauseCodeType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ETSI_ITS_CDD_CauseCodeType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_CauseCodeType;
asn_struct_free_f ETSI_ITS_CDD_CauseCodeType_free;
asn_struct_print_f ETSI_ITS_CDD_CauseCodeType_print;
asn_constr_check_f ETSI_ITS_CDD_CauseCodeType_constraint;
ber_type_decoder_f ETSI_ITS_CDD_CauseCodeType_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_CauseCodeType_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_CauseCodeType_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_CauseCodeType_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_CauseCodeType_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_CauseCodeType_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_CauseCodeType_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_CauseCodeType_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_CauseCodeType_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_CauseCodeType_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_CauseCodeType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_CauseCodeType_H_ */
#include "asn_internal.h"
