/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_VehicleRole_H_
#define	_ETSI_ITS_CDD_VehicleRole_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_VehicleRole {
	ETSI_ITS_CDD_VehicleRole_default	= 0,
	ETSI_ITS_CDD_VehicleRole_publicTransport	= 1,
	ETSI_ITS_CDD_VehicleRole_specialTransport	= 2,
	ETSI_ITS_CDD_VehicleRole_dangerousGoods	= 3,
	ETSI_ITS_CDD_VehicleRole_roadWork	= 4,
	ETSI_ITS_CDD_VehicleRole_rescue	= 5,
	ETSI_ITS_CDD_VehicleRole_emergency	= 6,
	ETSI_ITS_CDD_VehicleRole_safetyCar	= 7,
	ETSI_ITS_CDD_VehicleRole_agriculture	= 8,
	ETSI_ITS_CDD_VehicleRole_commercial	= 9,
	ETSI_ITS_CDD_VehicleRole_military	= 10,
	ETSI_ITS_CDD_VehicleRole_roadOperator	= 11,
	ETSI_ITS_CDD_VehicleRole_taxi	= 12,
	ETSI_ITS_CDD_VehicleRole_reserved1	= 13,
	ETSI_ITS_CDD_VehicleRole_reserved2	= 14,
	ETSI_ITS_CDD_VehicleRole_reserved3	= 15
} e_ETSI_ITS_CDD_VehicleRole;

/* ETSI-ITS-CDD_VehicleRole */
typedef long	 ETSI_ITS_CDD_VehicleRole_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_VehicleRole;
asn_struct_free_f ETSI_ITS_CDD_VehicleRole_free;
asn_struct_print_f ETSI_ITS_CDD_VehicleRole_print;
asn_constr_check_f ETSI_ITS_CDD_VehicleRole_constraint;
ber_type_decoder_f ETSI_ITS_CDD_VehicleRole_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_VehicleRole_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_VehicleRole_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_VehicleRole_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_VehicleRole_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_VehicleRole_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_VehicleRole_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_VehicleRole_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_VehicleRole_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_VehicleRole_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_VehicleRole_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_VehicleRole_H_ */
#include "asn_internal.h"
