/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_LaneType_H_
#define	_ETSI_ITS_CDD_LaneType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_LaneType {
	ETSI_ITS_CDD_LaneType_traffic	= 0,
	ETSI_ITS_CDD_LaneType_through	= 1,
	ETSI_ITS_CDD_LaneType_reversible	= 2,
	ETSI_ITS_CDD_LaneType_acceleration	= 3,
	ETSI_ITS_CDD_LaneType_deceleration	= 4,
	ETSI_ITS_CDD_LaneType_leftHandTurning	= 5,
	ETSI_ITS_CDD_LaneType_rightHandTurning	= 6,
	ETSI_ITS_CDD_LaneType_dedicatedVehicle	= 7,
	ETSI_ITS_CDD_LaneType_bus	= 8,
	ETSI_ITS_CDD_LaneType_taxi	= 9,
	ETSI_ITS_CDD_LaneType_hov	= 10,
	ETSI_ITS_CDD_LaneType_hot	= 11,
	ETSI_ITS_CDD_LaneType_pedestrian	= 12,
	ETSI_ITS_CDD_LaneType_cycleLane	= 13,
	ETSI_ITS_CDD_LaneType_median	= 14,
	ETSI_ITS_CDD_LaneType_striping	= 15,
	ETSI_ITS_CDD_LaneType_trackedVehicle	= 16,
	ETSI_ITS_CDD_LaneType_parking	= 17,
	ETSI_ITS_CDD_LaneType_emergency	= 18,
	ETSI_ITS_CDD_LaneType_verge	= 19,
	ETSI_ITS_CDD_LaneType_minimumRiskManoeuvre	= 20,
	ETSI_ITS_CDD_LaneType_unknown	= 31
} e_ETSI_ITS_CDD_LaneType;

/* ETSI-ITS-CDD_LaneType */
typedef long	 ETSI_ITS_CDD_LaneType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ETSI_ITS_CDD_LaneType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_LaneType;
asn_struct_free_f ETSI_ITS_CDD_LaneType_free;
asn_struct_print_f ETSI_ITS_CDD_LaneType_print;
asn_constr_check_f ETSI_ITS_CDD_LaneType_constraint;
ber_type_decoder_f ETSI_ITS_CDD_LaneType_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_LaneType_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_LaneType_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_LaneType_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_LaneType_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_LaneType_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_LaneType_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_LaneType_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_LaneType_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_LaneType_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_LaneType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_LaneType_H_ */
#include "asn_internal.h"
