/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_Iso3833VehicleType_H_
#define	_ETSI_ITS_CDD_Iso3833VehicleType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_Iso3833VehicleType {
	ETSI_ITS_CDD_Iso3833VehicleType_passengerCar	= 0,
	ETSI_ITS_CDD_Iso3833VehicleType_saloon	= 1,
	ETSI_ITS_CDD_Iso3833VehicleType_convertibleSaloon	= 2,
	ETSI_ITS_CDD_Iso3833VehicleType_pullmanSaloon	= 3,
	ETSI_ITS_CDD_Iso3833VehicleType_stationWagon	= 4,
	ETSI_ITS_CDD_Iso3833VehicleType_truckStationWagon	= 5,
	ETSI_ITS_CDD_Iso3833VehicleType_coupe	= 6,
	ETSI_ITS_CDD_Iso3833VehicleType_convertible	= 7,
	ETSI_ITS_CDD_Iso3833VehicleType_multipurposePassengerCar	= 8,
	ETSI_ITS_CDD_Iso3833VehicleType_forwardControlPassengerCar	= 9,
	ETSI_ITS_CDD_Iso3833VehicleType_specialPassengerCar	= 10,
	ETSI_ITS_CDD_Iso3833VehicleType_bus	= 11,
	ETSI_ITS_CDD_Iso3833VehicleType_minibus	= 12,
	ETSI_ITS_CDD_Iso3833VehicleType_urbanBus	= 13,
	ETSI_ITS_CDD_Iso3833VehicleType_interurbanCoach	= 14,
	ETSI_ITS_CDD_Iso3833VehicleType_longDistanceCoach	= 15,
	ETSI_ITS_CDD_Iso3833VehicleType_articulatedBus	= 16,
	ETSI_ITS_CDD_Iso3833VehicleType_trolleyBus	= 17,
	ETSI_ITS_CDD_Iso3833VehicleType_specialBus	= 18,
	ETSI_ITS_CDD_Iso3833VehicleType_commercialVehicle	= 19,
	ETSI_ITS_CDD_Iso3833VehicleType_specialCommercialVehicle	= 20,
	ETSI_ITS_CDD_Iso3833VehicleType_specialVehicle	= 21,
	ETSI_ITS_CDD_Iso3833VehicleType_trailingTowingVehicle	= 22,
	ETSI_ITS_CDD_Iso3833VehicleType_semiTrailerTowingVehicle	= 23,
	ETSI_ITS_CDD_Iso3833VehicleType_trailer	= 24,
	ETSI_ITS_CDD_Iso3833VehicleType_busTrailer	= 25,
	ETSI_ITS_CDD_Iso3833VehicleType_generalPurposeTrailer	= 26,
	ETSI_ITS_CDD_Iso3833VehicleType_caravan	= 27,
	ETSI_ITS_CDD_Iso3833VehicleType_specialTrailer	= 28,
	ETSI_ITS_CDD_Iso3833VehicleType_semiTrailer	= 29,
	ETSI_ITS_CDD_Iso3833VehicleType_busSemiTrailer	= 30,
	ETSI_ITS_CDD_Iso3833VehicleType_generalPurposeSemiTrailer	= 31,
	ETSI_ITS_CDD_Iso3833VehicleType_specialSemiTrailer	= 32,
	ETSI_ITS_CDD_Iso3833VehicleType_roadTrain	= 33,
	ETSI_ITS_CDD_Iso3833VehicleType_passengerRoadTrain	= 34,
	ETSI_ITS_CDD_Iso3833VehicleType_articulatedRoadTrain	= 35,
	ETSI_ITS_CDD_Iso3833VehicleType_doubleRoadTrain	= 36,
	ETSI_ITS_CDD_Iso3833VehicleType_compositeRoadTrain	= 37,
	ETSI_ITS_CDD_Iso3833VehicleType_specialRoadTrain	= 38,
	ETSI_ITS_CDD_Iso3833VehicleType_moped	= 39,
	ETSI_ITS_CDD_Iso3833VehicleType_motorCycle	= 40
} e_ETSI_ITS_CDD_Iso3833VehicleType;

/* ETSI-ITS-CDD_Iso3833VehicleType */
typedef long	 ETSI_ITS_CDD_Iso3833VehicleType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_Iso3833VehicleType;
asn_struct_free_f ETSI_ITS_CDD_Iso3833VehicleType_free;
asn_struct_print_f ETSI_ITS_CDD_Iso3833VehicleType_print;
asn_constr_check_f ETSI_ITS_CDD_Iso3833VehicleType_constraint;
ber_type_decoder_f ETSI_ITS_CDD_Iso3833VehicleType_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_Iso3833VehicleType_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_Iso3833VehicleType_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_Iso3833VehicleType_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_Iso3833VehicleType_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_Iso3833VehicleType_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_Iso3833VehicleType_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_Iso3833VehicleType_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_Iso3833VehicleType_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_Iso3833VehicleType_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_Iso3833VehicleType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_Iso3833VehicleType_H_ */
#include "asn_internal.h"
