/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "asn1/TS102894-2v211-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ETSI_ITS_CDD_StationType_H_
#define	_ETSI_ITS_CDD_StationType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ETSI_ITS_CDD_StationType {
	ETSI_ITS_CDD_StationType_unknown	= 0,
	ETSI_ITS_CDD_StationType_pedestrian	= 1,
	ETSI_ITS_CDD_StationType_cyclist	= 2,
	ETSI_ITS_CDD_StationType_moped	= 3,
	ETSI_ITS_CDD_StationType_motorcycle	= 4,
	ETSI_ITS_CDD_StationType_passengerCar	= 5,
	ETSI_ITS_CDD_StationType_bus	= 6,
	ETSI_ITS_CDD_StationType_lightTruck	= 7,
	ETSI_ITS_CDD_StationType_heavyTruck	= 8,
	ETSI_ITS_CDD_StationType_trailer	= 9,
	ETSI_ITS_CDD_StationType_specialVehicle	= 10,
	ETSI_ITS_CDD_StationType_tram	= 11,
	ETSI_ITS_CDD_StationType_lightVruVehicle	= 12,
	ETSI_ITS_CDD_StationType_animal	= 13,
	ETSI_ITS_CDD_StationType_roadSideUnit	= 15
} e_ETSI_ITS_CDD_StationType;

/* ETSI-ITS-CDD_StationType */
typedef long	 ETSI_ITS_CDD_StationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ETSI_ITS_CDD_StationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ETSI_ITS_CDD_StationType;
asn_struct_free_f ETSI_ITS_CDD_StationType_free;
asn_struct_print_f ETSI_ITS_CDD_StationType_print;
asn_constr_check_f ETSI_ITS_CDD_StationType_constraint;
ber_type_decoder_f ETSI_ITS_CDD_StationType_decode_ber;
der_type_encoder_f ETSI_ITS_CDD_StationType_encode_der;
xer_type_decoder_f ETSI_ITS_CDD_StationType_decode_xer;
xer_type_encoder_f ETSI_ITS_CDD_StationType_encode_xer;
jer_type_encoder_f ETSI_ITS_CDD_StationType_encode_jer;
oer_type_decoder_f ETSI_ITS_CDD_StationType_decode_oer;
oer_type_encoder_f ETSI_ITS_CDD_StationType_encode_oer;
per_type_decoder_f ETSI_ITS_CDD_StationType_decode_uper;
per_type_encoder_f ETSI_ITS_CDD_StationType_encode_uper;
per_type_decoder_f ETSI_ITS_CDD_StationType_decode_aper;
per_type_encoder_f ETSI_ITS_CDD_StationType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ETSI_ITS_CDD_StationType_H_ */
#include "asn_internal.h"
