/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "asn1/EN302637-3v131-DENM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ImpactReductionContainer_H_
#define	_ImpactReductionContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ITS-Container_HeightLonCarr.h"
#include "ITS-Container_PosLonCarr.h"
#include "ITS-Container_PositionOfPillars.h"
#include "ITS-Container_PosCentMass.h"
#include "ITS-Container_WheelBaseVehicle.h"
#include "ITS-Container_TurningRadius.h"
#include "ITS-Container_PosFrontAx.h"
#include "ITS-Container_PositionOfOccupants.h"
#include "ITS-Container_VehicleMass.h"
#include "ITS-Container_RequestResponseIndication.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ImpactReductionContainer */
typedef struct ImpactReductionContainer {
	ITS_Container_HeightLonCarr_t	 heightLonCarrLeft;
	ITS_Container_HeightLonCarr_t	 heightLonCarrRight;
	ITS_Container_PosLonCarr_t	 posLonCarrLeft;
	ITS_Container_PosLonCarr_t	 posLonCarrRight;
	ITS_Container_PositionOfPillars_t	 positionOfPillars;
	ITS_Container_PosCentMass_t	 posCentMass;
	ITS_Container_WheelBaseVehicle_t	 wheelBaseVehicle;
	ITS_Container_TurningRadius_t	 turningRadius;
	ITS_Container_PosFrontAx_t	 posFrontAx;
	ITS_Container_PositionOfOccupants_t	 positionOfOccupants;
	ITS_Container_VehicleMass_t	 vehicleMass;
	ITS_Container_RequestResponseIndication_t	 requestResponseIndication;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ImpactReductionContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ImpactReductionContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_ImpactReductionContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_ImpactReductionContainer_1[12];

#ifdef __cplusplus
}
#endif

#endif	/* _ImpactReductionContainer_H_ */
#include "asn_internal.h"
