/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_AltitudeConfidence_H_
#define	_ITS_Container_AltitudeConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITS_Container_AltitudeConfidence {
	ITS_Container_AltitudeConfidence_alt_000_01	= 0,
	ITS_Container_AltitudeConfidence_alt_000_02	= 1,
	ITS_Container_AltitudeConfidence_alt_000_05	= 2,
	ITS_Container_AltitudeConfidence_alt_000_10	= 3,
	ITS_Container_AltitudeConfidence_alt_000_20	= 4,
	ITS_Container_AltitudeConfidence_alt_000_50	= 5,
	ITS_Container_AltitudeConfidence_alt_001_00	= 6,
	ITS_Container_AltitudeConfidence_alt_002_00	= 7,
	ITS_Container_AltitudeConfidence_alt_005_00	= 8,
	ITS_Container_AltitudeConfidence_alt_010_00	= 9,
	ITS_Container_AltitudeConfidence_alt_020_00	= 10,
	ITS_Container_AltitudeConfidence_alt_050_00	= 11,
	ITS_Container_AltitudeConfidence_alt_100_00	= 12,
	ITS_Container_AltitudeConfidence_alt_200_00	= 13,
	ITS_Container_AltitudeConfidence_outOfRange	= 14,
	ITS_Container_AltitudeConfidence_unavailable	= 15
} e_ITS_Container_AltitudeConfidence;

/* ITS-Container_AltitudeConfidence */
typedef long	 ITS_Container_AltitudeConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITS_Container_AltitudeConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_AltitudeConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_ITS_Container_AltitudeConfidence_specs_1;
asn_struct_free_f ITS_Container_AltitudeConfidence_free;
asn_struct_print_f ITS_Container_AltitudeConfidence_print;
asn_constr_check_f ITS_Container_AltitudeConfidence_constraint;
ber_type_decoder_f ITS_Container_AltitudeConfidence_decode_ber;
der_type_encoder_f ITS_Container_AltitudeConfidence_encode_der;
xer_type_decoder_f ITS_Container_AltitudeConfidence_decode_xer;
xer_type_encoder_f ITS_Container_AltitudeConfidence_encode_xer;
jer_type_encoder_f ITS_Container_AltitudeConfidence_encode_jer;
oer_type_decoder_f ITS_Container_AltitudeConfidence_decode_oer;
oer_type_encoder_f ITS_Container_AltitudeConfidence_encode_oer;
per_type_decoder_f ITS_Container_AltitudeConfidence_decode_uper;
per_type_encoder_f ITS_Container_AltitudeConfidence_encode_uper;
per_type_decoder_f ITS_Container_AltitudeConfidence_decode_aper;
per_type_encoder_f ITS_Container_AltitudeConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_AltitudeConfidence_H_ */
#include "asn_internal.h"
