/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_ExteriorLights_H_
#define	_ITS_Container_ExteriorLights_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITS_Container_ExteriorLights {
	ITS_Container_ExteriorLights_lowBeamHeadlightsOn	= 0,
	ITS_Container_ExteriorLights_highBeamHeadlightsOn	= 1,
	ITS_Container_ExteriorLights_leftTurnSignalOn	= 2,
	ITS_Container_ExteriorLights_rightTurnSignalOn	= 3,
	ITS_Container_ExteriorLights_daytimeRunningLightsOn	= 4,
	ITS_Container_ExteriorLights_reverseLightOn	= 5,
	ITS_Container_ExteriorLights_fogLightOn	= 6,
	ITS_Container_ExteriorLights_parkingLightsOn	= 7
} e_ITS_Container_ExteriorLights;

/* ITS-Container_ExteriorLights */
typedef BIT_STRING_t	 ITS_Container_ExteriorLights_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITS_Container_ExteriorLights_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_ExteriorLights;
asn_struct_free_f ITS_Container_ExteriorLights_free;
asn_struct_print_f ITS_Container_ExteriorLights_print;
asn_constr_check_f ITS_Container_ExteriorLights_constraint;
ber_type_decoder_f ITS_Container_ExteriorLights_decode_ber;
der_type_encoder_f ITS_Container_ExteriorLights_encode_der;
xer_type_decoder_f ITS_Container_ExteriorLights_decode_xer;
xer_type_encoder_f ITS_Container_ExteriorLights_encode_xer;
jer_type_encoder_f ITS_Container_ExteriorLights_encode_jer;
oer_type_decoder_f ITS_Container_ExteriorLights_decode_oer;
oer_type_encoder_f ITS_Container_ExteriorLights_encode_oer;
per_type_decoder_f ITS_Container_ExteriorLights_decode_uper;
per_type_encoder_f ITS_Container_ExteriorLights_encode_uper;
per_type_decoder_f ITS_Container_ExteriorLights_decode_aper;
per_type_encoder_f ITS_Container_ExteriorLights_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_ExteriorLights_H_ */
#include "asn_internal.h"
