/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_PositionOfOccupants_H_
#define	_ITS_Container_PositionOfOccupants_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITS_Container_PositionOfOccupants {
	ITS_Container_PositionOfOccupants_row1LeftOccupied	= 0,
	ITS_Container_PositionOfOccupants_row1RightOccupied	= 1,
	ITS_Container_PositionOfOccupants_row1MidOccupied	= 2,
	ITS_Container_PositionOfOccupants_row1NotDetectable	= 3,
	ITS_Container_PositionOfOccupants_row1NotPresent	= 4,
	ITS_Container_PositionOfOccupants_row2LeftOccupied	= 5,
	ITS_Container_PositionOfOccupants_row2RightOccupied	= 6,
	ITS_Container_PositionOfOccupants_row2MidOccupied	= 7,
	ITS_Container_PositionOfOccupants_row2NotDetectable	= 8,
	ITS_Container_PositionOfOccupants_row2NotPresent	= 9,
	ITS_Container_PositionOfOccupants_row3LeftOccupied	= 10,
	ITS_Container_PositionOfOccupants_row3RightOccupied	= 11,
	ITS_Container_PositionOfOccupants_row3MidOccupied	= 12,
	ITS_Container_PositionOfOccupants_row3NotDetectable	= 13,
	ITS_Container_PositionOfOccupants_row3NotPresent	= 14,
	ITS_Container_PositionOfOccupants_row4LeftOccupied	= 15,
	ITS_Container_PositionOfOccupants_row4RightOccupied	= 16,
	ITS_Container_PositionOfOccupants_row4MidOccupied	= 17,
	ITS_Container_PositionOfOccupants_row4NotDetectable	= 18,
	ITS_Container_PositionOfOccupants_row4NotPresent	= 19
} e_ITS_Container_PositionOfOccupants;

/* ITS-Container_PositionOfOccupants */
typedef BIT_STRING_t	 ITS_Container_PositionOfOccupants_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITS_Container_PositionOfOccupants_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_PositionOfOccupants;
asn_struct_free_f ITS_Container_PositionOfOccupants_free;
asn_struct_print_f ITS_Container_PositionOfOccupants_print;
asn_constr_check_f ITS_Container_PositionOfOccupants_constraint;
ber_type_decoder_f ITS_Container_PositionOfOccupants_decode_ber;
der_type_encoder_f ITS_Container_PositionOfOccupants_encode_der;
xer_type_decoder_f ITS_Container_PositionOfOccupants_decode_xer;
xer_type_encoder_f ITS_Container_PositionOfOccupants_encode_xer;
jer_type_encoder_f ITS_Container_PositionOfOccupants_encode_jer;
oer_type_decoder_f ITS_Container_PositionOfOccupants_decode_oer;
oer_type_encoder_f ITS_Container_PositionOfOccupants_encode_oer;
per_type_decoder_f ITS_Container_PositionOfOccupants_decode_uper;
per_type_encoder_f ITS_Container_PositionOfOccupants_encode_uper;
per_type_decoder_f ITS_Container_PositionOfOccupants_decode_aper;
per_type_encoder_f ITS_Container_PositionOfOccupants_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_PositionOfOccupants_H_ */
#include "asn_internal.h"
