/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_CauseCodeType_H_
#define	_ITS_Container_CauseCodeType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITS_Container_CauseCodeType {
	ITS_Container_CauseCodeType_reserved	= 0,
	ITS_Container_CauseCodeType_trafficCondition	= 1,
	ITS_Container_CauseCodeType_accident	= 2,
	ITS_Container_CauseCodeType_roadworks	= 3,
	ITS_Container_CauseCodeType_impassability	= 5,
	ITS_Container_CauseCodeType_adverseWeatherCondition_Adhesion	= 6,
	ITS_Container_CauseCodeType_aquaplannning	= 7,
	ITS_Container_CauseCodeType_hazardousLocation_SurfaceCondition	= 9,
	ITS_Container_CauseCodeType_hazardousLocation_ObstacleOnTheRoad	= 10,
	ITS_Container_CauseCodeType_hazardousLocation_AnimalOnTheRoad	= 11,
	ITS_Container_CauseCodeType_humanPresenceOnTheRoad	= 12,
	ITS_Container_CauseCodeType_wrongWayDriving	= 14,
	ITS_Container_CauseCodeType_rescueAndRecoveryWorkInProgress	= 15,
	ITS_Container_CauseCodeType_adverseWeatherCondition_ExtremeWeatherCondition	= 17,
	ITS_Container_CauseCodeType_adverseWeatherCondition_Visibility	= 18,
	ITS_Container_CauseCodeType_adverseWeatherCondition_Precipitation	= 19,
	ITS_Container_CauseCodeType_slowVehicle	= 26,
	ITS_Container_CauseCodeType_dangerousEndOfQueue	= 27,
	ITS_Container_CauseCodeType_vehicleBreakdown	= 91,
	ITS_Container_CauseCodeType_postCrash	= 92,
	ITS_Container_CauseCodeType_humanProblem	= 93,
	ITS_Container_CauseCodeType_stationaryVehicle	= 94,
	ITS_Container_CauseCodeType_emergencyVehicleApproaching	= 95,
	ITS_Container_CauseCodeType_hazardousLocation_DangerousCurve	= 96,
	ITS_Container_CauseCodeType_collisionRisk	= 97,
	ITS_Container_CauseCodeType_signalViolation	= 98,
	ITS_Container_CauseCodeType_dangerousSituation	= 99
} e_ITS_Container_CauseCodeType;

/* ITS-Container_CauseCodeType */
typedef long	 ITS_Container_CauseCodeType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITS_Container_CauseCodeType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_CauseCodeType;
asn_struct_free_f ITS_Container_CauseCodeType_free;
asn_struct_print_f ITS_Container_CauseCodeType_print;
asn_constr_check_f ITS_Container_CauseCodeType_constraint;
ber_type_decoder_f ITS_Container_CauseCodeType_decode_ber;
der_type_encoder_f ITS_Container_CauseCodeType_encode_der;
xer_type_decoder_f ITS_Container_CauseCodeType_decode_xer;
xer_type_encoder_f ITS_Container_CauseCodeType_encode_xer;
jer_type_encoder_f ITS_Container_CauseCodeType_encode_jer;
oer_type_decoder_f ITS_Container_CauseCodeType_decode_oer;
oer_type_encoder_f ITS_Container_CauseCodeType_encode_oer;
per_type_decoder_f ITS_Container_CauseCodeType_decode_uper;
per_type_encoder_f ITS_Container_CauseCodeType_encode_uper;
per_type_decoder_f ITS_Container_CauseCodeType_decode_aper;
per_type_encoder_f ITS_Container_CauseCodeType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_CauseCodeType_H_ */
#include "asn_internal.h"
