/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_DigitalMap_H_
#define	_ITS_Container_DigitalMap_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReferencePosition;

/* ITS-Container_DigitalMap */
typedef struct ITS_Container_DigitalMap {
	A_SEQUENCE_OF(struct ReferencePosition) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ITS_Container_DigitalMap_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_DigitalMap;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ITS-Container_ReferencePosition.h"

#endif	/* _ITS_Container_DigitalMap_H_ */
#include "asn_internal.h"
