/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_DangerousGoodsBasic_H_
#define	_ITS_Container_DangerousGoodsBasic_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITS_Container_DangerousGoodsBasic {
	ITS_Container_DangerousGoodsBasic_explosives1	= 0,
	ITS_Container_DangerousGoodsBasic_explosives2	= 1,
	ITS_Container_DangerousGoodsBasic_explosives3	= 2,
	ITS_Container_DangerousGoodsBasic_explosives4	= 3,
	ITS_Container_DangerousGoodsBasic_explosives5	= 4,
	ITS_Container_DangerousGoodsBasic_explosives6	= 5,
	ITS_Container_DangerousGoodsBasic_flammableGases	= 6,
	ITS_Container_DangerousGoodsBasic_nonFlammableGases	= 7,
	ITS_Container_DangerousGoodsBasic_toxicGases	= 8,
	ITS_Container_DangerousGoodsBasic_flammableLiquids	= 9,
	ITS_Container_DangerousGoodsBasic_flammableSolids	= 10,
	ITS_Container_DangerousGoodsBasic_substancesLiableToSpontaneousCombustion	= 11,
	ITS_Container_DangerousGoodsBasic_substancesEmittingFlammableGasesUponContactWithWater	= 12,
	ITS_Container_DangerousGoodsBasic_oxidizingSubstances	= 13,
	ITS_Container_DangerousGoodsBasic_organicPeroxides	= 14,
	ITS_Container_DangerousGoodsBasic_toxicSubstances	= 15,
	ITS_Container_DangerousGoodsBasic_infectiousSubstances	= 16,
	ITS_Container_DangerousGoodsBasic_radioactiveMaterial	= 17,
	ITS_Container_DangerousGoodsBasic_corrosiveSubstances	= 18,
	ITS_Container_DangerousGoodsBasic_miscellaneousDangerousSubstances	= 19
} e_ITS_Container_DangerousGoodsBasic;

/* ITS-Container_DangerousGoodsBasic */
typedef long	 ITS_Container_DangerousGoodsBasic_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITS_Container_DangerousGoodsBasic_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_DangerousGoodsBasic;
extern const asn_INTEGER_specifics_t asn_SPC_ITS_Container_DangerousGoodsBasic_specs_1;
asn_struct_free_f ITS_Container_DangerousGoodsBasic_free;
asn_struct_print_f ITS_Container_DangerousGoodsBasic_print;
asn_constr_check_f ITS_Container_DangerousGoodsBasic_constraint;
ber_type_decoder_f ITS_Container_DangerousGoodsBasic_decode_ber;
der_type_encoder_f ITS_Container_DangerousGoodsBasic_encode_der;
xer_type_decoder_f ITS_Container_DangerousGoodsBasic_decode_xer;
xer_type_encoder_f ITS_Container_DangerousGoodsBasic_encode_xer;
jer_type_encoder_f ITS_Container_DangerousGoodsBasic_encode_jer;
oer_type_decoder_f ITS_Container_DangerousGoodsBasic_decode_oer;
oer_type_encoder_f ITS_Container_DangerousGoodsBasic_encode_oer;
per_type_decoder_f ITS_Container_DangerousGoodsBasic_decode_uper;
per_type_encoder_f ITS_Container_DangerousGoodsBasic_encode_uper;
per_type_decoder_f ITS_Container_DangerousGoodsBasic_decode_aper;
per_type_encoder_f ITS_Container_DangerousGoodsBasic_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_DangerousGoodsBasic_H_ */
#include "asn_internal.h"
