/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_CurvatureConfidence_H_
#define	_ITS_Container_CurvatureConfidence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITS_Container_CurvatureConfidence {
	ITS_Container_CurvatureConfidence_onePerMeter_0_00002	= 0,
	ITS_Container_CurvatureConfidence_onePerMeter_0_0001	= 1,
	ITS_Container_CurvatureConfidence_onePerMeter_0_0005	= 2,
	ITS_Container_CurvatureConfidence_onePerMeter_0_002	= 3,
	ITS_Container_CurvatureConfidence_onePerMeter_0_01	= 4,
	ITS_Container_CurvatureConfidence_onePerMeter_0_1	= 5,
	ITS_Container_CurvatureConfidence_outOfRange	= 6,
	ITS_Container_CurvatureConfidence_unavailable	= 7
} e_ITS_Container_CurvatureConfidence;

/* ITS-Container_CurvatureConfidence */
typedef long	 ITS_Container_CurvatureConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITS_Container_CurvatureConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_CurvatureConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_ITS_Container_CurvatureConfidence_specs_1;
asn_struct_free_f ITS_Container_CurvatureConfidence_free;
asn_struct_print_f ITS_Container_CurvatureConfidence_print;
asn_constr_check_f ITS_Container_CurvatureConfidence_constraint;
ber_type_decoder_f ITS_Container_CurvatureConfidence_decode_ber;
der_type_encoder_f ITS_Container_CurvatureConfidence_encode_der;
xer_type_decoder_f ITS_Container_CurvatureConfidence_decode_xer;
xer_type_encoder_f ITS_Container_CurvatureConfidence_encode_xer;
jer_type_encoder_f ITS_Container_CurvatureConfidence_encode_jer;
oer_type_decoder_f ITS_Container_CurvatureConfidence_decode_oer;
oer_type_encoder_f ITS_Container_CurvatureConfidence_encode_oer;
per_type_decoder_f ITS_Container_CurvatureConfidence_decode_uper;
per_type_encoder_f ITS_Container_CurvatureConfidence_encode_uper;
per_type_decoder_f ITS_Container_CurvatureConfidence_decode_aper;
per_type_encoder_f ITS_Container_CurvatureConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_CurvatureConfidence_H_ */
#include "asn_internal.h"
