/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_VehicleRole_H_
#define	_ITS_Container_VehicleRole_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITS_Container_VehicleRole {
	ITS_Container_VehicleRole_default	= 0,
	ITS_Container_VehicleRole_publicTransport	= 1,
	ITS_Container_VehicleRole_specialTransport	= 2,
	ITS_Container_VehicleRole_dangerousGoods	= 3,
	ITS_Container_VehicleRole_roadWork	= 4,
	ITS_Container_VehicleRole_rescue	= 5,
	ITS_Container_VehicleRole_emergency	= 6,
	ITS_Container_VehicleRole_safetyCar	= 7,
	ITS_Container_VehicleRole_agriculture	= 8,
	ITS_Container_VehicleRole_commercial	= 9,
	ITS_Container_VehicleRole_military	= 10,
	ITS_Container_VehicleRole_roadOperator	= 11,
	ITS_Container_VehicleRole_taxi	= 12,
	ITS_Container_VehicleRole_reserved1	= 13,
	ITS_Container_VehicleRole_reserved2	= 14,
	ITS_Container_VehicleRole_reserved3	= 15
} e_ITS_Container_VehicleRole;

/* ITS-Container_VehicleRole */
typedef long	 ITS_Container_VehicleRole_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITS_Container_VehicleRole_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_VehicleRole;
extern const asn_INTEGER_specifics_t asn_SPC_ITS_Container_VehicleRole_specs_1;
asn_struct_free_f ITS_Container_VehicleRole_free;
asn_struct_print_f ITS_Container_VehicleRole_print;
asn_constr_check_f ITS_Container_VehicleRole_constraint;
ber_type_decoder_f ITS_Container_VehicleRole_decode_ber;
der_type_encoder_f ITS_Container_VehicleRole_encode_der;
xer_type_decoder_f ITS_Container_VehicleRole_decode_xer;
xer_type_encoder_f ITS_Container_VehicleRole_encode_xer;
jer_type_encoder_f ITS_Container_VehicleRole_encode_jer;
oer_type_decoder_f ITS_Container_VehicleRole_decode_oer;
oer_type_encoder_f ITS_Container_VehicleRole_encode_oer;
per_type_decoder_f ITS_Container_VehicleRole_decode_uper;
per_type_encoder_f ITS_Container_VehicleRole_encode_uper;
per_type_decoder_f ITS_Container_VehicleRole_decode_aper;
per_type_encoder_f ITS_Container_VehicleRole_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_VehicleRole_H_ */
#include "asn_internal.h"
