/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_ItsPduHeader_H_
#define	_ITS_Container_ItsPduHeader_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "ITS-Container_StationID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITS_Container_ItsPduHeader__messageID {
	ITS_Container_ItsPduHeader__messageID_denm	= 1,
	ITS_Container_ItsPduHeader__messageID_cam	= 2,
	ITS_Container_ItsPduHeader__messageID_poi	= 3,
	ITS_Container_ItsPduHeader__messageID_spatem	= 4,
	ITS_Container_ItsPduHeader__messageID_mapem	= 5,
	ITS_Container_ItsPduHeader__messageID_ivim	= 6,
	ITS_Container_ItsPduHeader__messageID_ev_rsr	= 7,
	ITS_Container_ItsPduHeader__messageID_tistpgtransaction	= 8,
	ITS_Container_ItsPduHeader__messageID_srem	= 9,
	ITS_Container_ItsPduHeader__messageID_ssem	= 10,
	ITS_Container_ItsPduHeader__messageID_evcsn	= 11,
	ITS_Container_ItsPduHeader__messageID_saem	= 12,
	ITS_Container_ItsPduHeader__messageID_rtcmem	= 13
} e_ITS_Container_ItsPduHeader__messageID;

/* ITS-Container_ItsPduHeader */
typedef struct ITS_Container_ItsPduHeader {
	long	 protocolVersion;
	long	 messageID;
	ITS_Container_StationID_t	 stationID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ITS_Container_ItsPduHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_ItsPduHeader;
extern asn_SEQUENCE_specifics_t asn_SPC_ITS_Container_ItsPduHeader_specs_1;
extern asn_TYPE_member_t asn_MBR_ITS_Container_ItsPduHeader_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_ItsPduHeader_H_ */
#include "asn_internal.h"
