/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_LongitudinalAcceleration_H_
#define	_ITS_Container_LongitudinalAcceleration_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ITS-Container_LongitudinalAccelerationValue.h"
#include "ITS-Container_AccelerationConfidence.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ITS-Container_LongitudinalAcceleration */
typedef struct ITS_Container_LongitudinalAcceleration {
	ITS_Container_LongitudinalAccelerationValue_t	 longitudinalAccelerationValue;
	ITS_Container_AccelerationConfidence_t	 longitudinalAccelerationConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ITS_Container_LongitudinalAcceleration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_LongitudinalAcceleration;
extern asn_SEQUENCE_specifics_t asn_SPC_ITS_Container_LongitudinalAcceleration_specs_1;
extern asn_TYPE_member_t asn_MBR_ITS_Container_LongitudinalAcceleration_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_LongitudinalAcceleration_H_ */
#include "asn_internal.h"
