/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "asn1/TS102894-2v131-CDD.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ITS_Container_PtActivation_H_
#define	_ITS_Container_PtActivation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ITS-Container_PtActivationType.h"
#include "ITS-Container_PtActivationData.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ITS-Container_PtActivation */
typedef struct ITS_Container_PtActivation {
	ITS_Container_PtActivationType_t	 ptActivationType;
	ITS_Container_PtActivationData_t	 ptActivationData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ITS_Container_PtActivation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_PtActivation;
extern asn_SEQUENCE_specifics_t asn_SPC_ITS_Container_PtActivation_specs_1;
extern asn_TYPE_member_t asn_MBR_ITS_Container_PtActivation_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_PtActivation_H_ */
#include "asn_internal.h"
