/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "build.asn1/iso/ISO19321.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_IVI_Direction_H_
#define	_IVI_Direction_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IVI_Direction {
	IVI_Direction_sameDirection	= 0,
	IVI_Direction_oppositeDirection	= 1,
	IVI_Direction_bothDirections	= 2,
	IVI_Direction_valueNotUsed	= 3
} e_IVI_Direction;

/* IVI_Direction */
typedef long	 IVI_Direction_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_IVI_Direction_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_IVI_Direction;
asn_struct_free_f IVI_Direction_free;
asn_struct_print_f IVI_Direction_print;
asn_constr_check_f IVI_Direction_constraint;
ber_type_decoder_f IVI_Direction_decode_ber;
der_type_encoder_f IVI_Direction_encode_der;
xer_type_decoder_f IVI_Direction_decode_xer;
xer_type_encoder_f IVI_Direction_encode_xer;
jer_type_encoder_f IVI_Direction_encode_jer;
oer_type_decoder_f IVI_Direction_decode_oer;
oer_type_encoder_f IVI_Direction_encode_oer;
per_type_decoder_f IVI_Direction_decode_uper;
per_type_encoder_f IVI_Direction_encode_uper;
per_type_decoder_f IVI_Direction_decode_aper;
per_type_encoder_f IVI_Direction_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _IVI_Direction_H_ */
#include "asn_internal.h"
