/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "build.asn1/iso/ISO19321.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_IVI_MapReference_H_
#define	_IVI_MapReference_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RoadSegmentReferenceID.h"
#include "IntersectionReferenceID.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IVI_MapReference_PR {
	IVI_MapReference_PR_NOTHING,	/* No components present */
	IVI_MapReference_PR_roadsegment,
	IVI_MapReference_PR_intersection
} IVI_MapReference_PR;

/* IVI_MapReference */
typedef struct IVI_MapReference {
	IVI_MapReference_PR present;
	union IVI_MapReference_u {
		RoadSegmentReferenceID_t	 roadsegment;
		IntersectionReferenceID_t	 intersection;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IVI_MapReference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IVI_MapReference;
extern asn_CHOICE_specifics_t asn_SPC_IVI_MapReference_specs_1;
extern asn_TYPE_member_t asn_MBR_IVI_MapReference_1[2];
extern asn_per_constraints_t asn_PER_type_IVI_MapReference_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _IVI_MapReference_H_ */
#include "asn_internal.h"
