/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_NonIslandLanePosition_H_
#define	_NonIslandLanePosition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OffRoadLanePosition.h"
#include "LanePosition.h"
#include "MapPosition.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NonIslandLanePosition_PR {
	NonIslandLanePosition_PR_NOTHING,	/* No components present */
	NonIslandLanePosition_PR_offRoadLanePosition,
	NonIslandLanePosition_PR_vehicularLanePosition,
	NonIslandLanePosition_PR_mapPosition
	/* Extensions may appear below */
	
} NonIslandLanePosition_PR;

/* NonIslandLanePosition */
typedef struct NonIslandLanePosition {
	NonIslandLanePosition_PR present;
	union NonIslandLanePosition_u {
		OffRoadLanePosition_t	 offRoadLanePosition;
		LanePosition_t	 vehicularLanePosition;
		MapPosition_t	 mapPosition;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NonIslandLanePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NonIslandLanePosition;
extern asn_CHOICE_specifics_t asn_SPC_NonIslandLanePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_NonIslandLanePosition_1[3];
extern asn_per_constraints_t asn_PER_type_NonIslandLanePosition_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NonIslandLanePosition_H_ */
#include "asn_internal.h"
