/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_OffRoadLanePosition_H_
#define	_OffRoadLanePosition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OffRoadLanePosition {
	OffRoadLanePosition_unavailable	= 0,
	OffRoadLanePosition_sidewalk	= 1,
	OffRoadLanePosition_parkingLane	= 2,
	OffRoadLanePosition_bikeLane	= 3,
	OffRoadLanePosition_max	= 15
} e_OffRoadLanePosition;

/* OffRoadLanePosition */
typedef long	 OffRoadLanePosition_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_OffRoadLanePosition_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_OffRoadLanePosition;
extern const asn_INTEGER_specifics_t asn_SPC_OffRoadLanePosition_specs_1;
asn_struct_free_f OffRoadLanePosition_free;
asn_struct_print_f OffRoadLanePosition_print;
asn_constr_check_f OffRoadLanePosition_constraint;
ber_type_decoder_f OffRoadLanePosition_decode_ber;
der_type_encoder_f OffRoadLanePosition_encode_der;
xer_type_decoder_f OffRoadLanePosition_decode_xer;
xer_type_encoder_f OffRoadLanePosition_encode_xer;
oer_type_decoder_f OffRoadLanePosition_decode_oer;
oer_type_encoder_f OffRoadLanePosition_encode_oer;
per_type_decoder_f OffRoadLanePosition_decode_uper;
per_type_encoder_f OffRoadLanePosition_encode_uper;
per_type_decoder_f OffRoadLanePosition_decode_aper;
per_type_encoder_f OffRoadLanePosition_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _OffRoadLanePosition_H_ */
#include "asn_internal.h"
