/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "asn1/EN302637-2v141-CAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_RoadWorksContainerBasic_H_
#define	_RoadWorksContainerBasic_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ITS-Container_RoadworksSubCauseCode.h"
#include "ITS-Container_LightBarSirenInUse.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ITS_Container_ClosedLanes;

/* RoadWorksContainerBasic */
typedef struct RoadWorksContainerBasic {
	ITS_Container_RoadworksSubCauseCode_t	*roadworksSubCauseCode;	/* OPTIONAL */
	ITS_Container_LightBarSirenInUse_t	 lightBarSirenInUse;
	struct ITS_Container_ClosedLanes	*closedLanes;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadWorksContainerBasic_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadWorksContainerBasic;
extern asn_SEQUENCE_specifics_t asn_SPC_RoadWorksContainerBasic_specs_1;
extern asn_TYPE_member_t asn_MBR_RoadWorksContainerBasic_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ITS-Container_ClosedLanes.h"

#endif	/* _RoadWorksContainerBasic_H_ */
#include "asn_internal.h"
