/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "asn1/EN302637-2v141-CAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SafetyCarContainer_H_
#define	_SafetyCarContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ITS-Container_LightBarSirenInUse.h"
#include "ITS-Container_TrafficRule.h"
#include "ITS-Container_SpeedLimit.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ITS_Container_CauseCode;

/* SafetyCarContainer */
typedef struct SafetyCarContainer {
	ITS_Container_LightBarSirenInUse_t	 lightBarSirenInUse;
	struct ITS_Container_CauseCode	*incidentIndication;	/* OPTIONAL */
	ITS_Container_TrafficRule_t	*trafficRule;	/* OPTIONAL */
	ITS_Container_SpeedLimit_t	*speedLimit;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SafetyCarContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SafetyCarContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_SafetyCarContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_SafetyCarContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ITS-Container_CauseCode.h"

#endif	/* _SafetyCarContainer_H_ */
#include "asn_internal.h"
