/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SequenceOfVruPathPoint_H_
#define	_SequenceOfVruPathPoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VruPathPoint;

/* SequenceOfVruPathPoint */
typedef struct SequenceOfVruPathPoint {
	A_SEQUENCE_OF(struct VruPathPoint) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfVruPathPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SequenceOfVruPathPoint;
extern asn_SET_OF_specifics_t asn_SPC_SequenceOfVruPathPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_SequenceOfVruPathPoint_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VruPathPoint.h"

#endif	/* _SequenceOfVruPathPoint_H_ */
#include "asn_internal.h"
