/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "asn1/EN302637-3v131-DENM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SituationContainer_H_
#define	_SituationContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ITS-Container_InformationQuality.h"
#include "ITS-Container_CauseCode.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CauseCode;
struct EventHistory;

/* SituationContainer */
typedef struct SituationContainer {
	ITS_Container_InformationQuality_t	 informationQuality;
	ITS_Container_CauseCode_t	 eventType;
	struct CauseCode	*linkedCause;	/* OPTIONAL */
	struct EventHistory	*eventHistory;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SituationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SituationContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_SituationContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_SituationContainer_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ITS-Container_CauseCode.h"
#include "ITS-Container_EventHistory.h"

#endif	/* _SituationContainer_H_ */
#include "asn_internal.h"
