/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_StationSafeDistanceIndication_H_
#define	_StationSafeDistanceIndication_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* StationSafeDistanceIndication */
typedef BOOLEAN_t	 StationSafeDistanceIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StationSafeDistanceIndication;
asn_struct_free_f StationSafeDistanceIndication_free;
asn_struct_print_f StationSafeDistanceIndication_print;
asn_constr_check_f StationSafeDistanceIndication_constraint;
ber_type_decoder_f StationSafeDistanceIndication_decode_ber;
der_type_encoder_f StationSafeDistanceIndication_encode_der;
xer_type_decoder_f StationSafeDistanceIndication_decode_xer;
xer_type_encoder_f StationSafeDistanceIndication_encode_xer;
oer_type_decoder_f StationSafeDistanceIndication_decode_oer;
oer_type_encoder_f StationSafeDistanceIndication_encode_oer;
per_type_decoder_f StationSafeDistanceIndication_decode_uper;
per_type_encoder_f StationSafeDistanceIndication_encode_uper;
per_type_decoder_f StationSafeDistanceIndication_decode_aper;
per_type_encoder_f StationSafeDistanceIndication_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _StationSafeDistanceIndication_H_ */
#include "asn_internal.h"
