/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "asn1/EN302637-3v131-DENM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_StationaryVehicleContainer_H_
#define	_StationaryVehicleContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ITS-Container_StationarySince.h"
#include "ITS-Container_NumberOfOccupants.h"
#include "ITS-Container_EnergyStorageType.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CauseCode;
struct DangerousGoodsExtended;
struct VehicleIdentification;

/* StationaryVehicleContainer */
typedef struct StationaryVehicleContainer {
	ITS_Container_StationarySince_t	*stationarySince;	/* OPTIONAL */
	struct CauseCode	*stationaryCause;	/* OPTIONAL */
	struct DangerousGoodsExtended	*carryingDangerousGoods;	/* OPTIONAL */
	ITS_Container_NumberOfOccupants_t	*numberOfOccupants;	/* OPTIONAL */
	struct VehicleIdentification	*vehicleIdentification;	/* OPTIONAL */
	ITS_Container_EnergyStorageType_t	*energyStorageType;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StationaryVehicleContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StationaryVehicleContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_StationaryVehicleContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_StationaryVehicleContainer_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ITS-Container_CauseCode.h"
#include "ITS-Container_DangerousGoodsExtended.h"
#include "ITS-Container_VehicleIdentification.h"

#endif	/* _StationaryVehicleContainer_H_ */
#include "asn_internal.h"
