/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VruExteriorLights_H_
#define	_VruExteriorLights_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VruSpecificExteriorLights.h"
#include "ExteriorLights.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VruExteriorLights */
typedef struct VruExteriorLights {
	VruSpecificExteriorLights_t	 vruSpecific;
	ExteriorLights_t	 vehicular;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VruExteriorLights_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruExteriorLights;
extern asn_SEQUENCE_specifics_t asn_SPC_VruExteriorLights_specs_1;
extern asn_TYPE_member_t asn_MBR_VruExteriorLights_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _VruExteriorLights_H_ */
#include "asn_internal.h"
