/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VruLanePosition_H_
#define	_VruLanePosition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OffRoadLanePosition.h"
#include "LanePosition.h"
#include "TrafficIslandPosition.h"
#include "MapPosition.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VruLanePosition_PR {
	VruLanePosition_PR_NOTHING,	/* No components present */
	VruLanePosition_PR_offRoadLanePosition,
	VruLanePosition_PR_vehicularLanePosition,
	VruLanePosition_PR_trafficIslandPosition,
	VruLanePosition_PR_mapPosition
	/* Extensions may appear below */
	
} VruLanePosition_PR;

/* VruLanePosition */
typedef struct VruLanePosition {
	VruLanePosition_PR present;
	union VruLanePosition_u {
		OffRoadLanePosition_t	 offRoadLanePosition;
		LanePosition_t	 vehicularLanePosition;
		TrafficIslandPosition_t	 trafficIslandPosition;
		MapPosition_t	 mapPosition;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VruLanePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruLanePosition;
extern asn_CHOICE_specifics_t asn_SPC_VruLanePosition_specs_1;
extern asn_TYPE_member_t asn_MBR_VruLanePosition_1[4];
extern asn_per_constraints_t asn_PER_type_VruLanePosition_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _VruLanePosition_H_ */
#include "asn_internal.h"
