/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VruProfile_H_
#define	_VruProfile_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VruProfile {
	VruProfile_unavailable	= 0,
	VruProfile_pedestrian	= 1,
	VruProfile_cyclist	= 2,
	VruProfile_motorcyclist	= 3,
	VruProfile_animal	= 4,
	VruProfile_max	= 15
} e_VruProfile;

/* VruProfile */
typedef long	 VruProfile_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruProfile;
asn_struct_free_f VruProfile_free;
asn_struct_print_f VruProfile_print;
asn_constr_check_f VruProfile_constraint;
ber_type_decoder_f VruProfile_decode_ber;
der_type_encoder_f VruProfile_encode_der;
xer_type_decoder_f VruProfile_decode_xer;
xer_type_encoder_f VruProfile_encode_xer;
oer_type_decoder_f VruProfile_decode_oer;
oer_type_encoder_f VruProfile_encode_oer;
per_type_decoder_f VruProfile_decode_uper;
per_type_encoder_f VruProfile_encode_uper;
per_type_decoder_f VruProfile_decode_aper;
per_type_encoder_f VruProfile_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VruProfile_H_ */
#include "asn_internal.h"
