/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VruPathPoint_H_
#define	_VruPathPoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ReferencePosition.h"
#include "PathDeltaTime.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VruPathPoint */
typedef struct VruPathPoint {
	ReferencePosition_t	 pathPosition;
	PathDeltaTime_t	*pathDeltaTime;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VruPathPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruPathPoint;
extern asn_SEQUENCE_specifics_t asn_SPC_VruPathPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_VruPathPoint_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _VruPathPoint_H_ */
#include "asn_internal.h"
