/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "asn1/TS103300-3v211-VAM.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VruRollAngle_H_
#define	_VruRollAngle_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Heading.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VruRollAngle */
typedef Heading_t	 VruRollAngle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VruRollAngle;
asn_struct_free_f VruRollAngle_free;
asn_struct_print_f VruRollAngle_print;
asn_constr_check_f VruRollAngle_constraint;
ber_type_decoder_f VruRollAngle_decode_ber;
der_type_encoder_f VruRollAngle_encode_der;
xer_type_decoder_f VruRollAngle_decode_xer;
xer_type_encoder_f VruRollAngle_encode_xer;
oer_type_decoder_f VruRollAngle_decode_oer;
oer_type_encoder_f VruRollAngle_encode_oer;
per_type_decoder_f VruRollAngle_decode_uper;
per_type_encoder_f VruRollAngle_encode_uper;
per_type_decoder_f VruRollAngle_decode_aper;
per_type_encoder_f VruRollAngle_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VruRollAngle_H_ */
#include "asn_internal.h"
